//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: MainFrame.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _PIEZO_PIEZO_MAINFRAME_BASE_CLASSES_H
#define _PIEZO_PIEZO_MAINFRAME_BASE_CLASSES_H

#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/statbmp.h>
#include <wx/stattext.h>
#include <wx/textctrl.h>
#include <wx/button.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif


class MainFrameBase : public wxFrame
{
protected:
    wxPanel* m_panel5;
    wxStaticBitmap* m_staticBitmap95;
    wxStaticBitmap* m_staticBitmap99;
    wxStaticText* m_textomassa;
    wxTextCtrl* m_controlMassa;
    wxStaticText* m_textoDm;
    wxTextCtrl* m_controlDm;
    wxStaticText* m_textoCm;
    wxTextCtrl* m_controlCm;
    wxStaticText* m_textoAlfa;
    wxTextCtrl* m_controlAlfa;
    wxStaticText* m_textoCp;
    wxTextCtrl* m_controlCp;
    wxStaticText* m_textoR;
    wxTextCtrl* m_controlR;
    wxStaticText* m_textoPasso;
    wxTextCtrl* m_controlPasso;
    wxStaticText* m_textoTempSimu;
    wxTextCtrl* m_controlTempSimu;
    wxStaticText* m_textoFrequencia;
    wxTextCtrl* m_controlFrequencia;
    wxStaticText* m_textoDeflexao;
    wxTextCtrl* m_controlDeflexao;
    wxStaticText* m_textoF;
    wxTextCtrl* m_controlF;
    wxButton* m_btnSimular;
    wxButton* m_btnLimpar;

protected:
    virtual void OnbtnSimularClick(wxCommandEvent& event) { event.Skip(); }
    virtual void OnbtnLimparClick(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticBitmap* GetStaticBitmap95() { return m_staticBitmap95; }
    wxStaticBitmap* GetStaticBitmap99() { return m_staticBitmap99; }
    wxStaticText* GetTextomassa() { return m_textomassa; }
    wxTextCtrl* GetControlMassa() { return m_controlMassa; }
    wxStaticText* GetTextoDm() { return m_textoDm; }
    wxTextCtrl* GetControlDm() { return m_controlDm; }
    wxStaticText* GetTextoCm() { return m_textoCm; }
    wxTextCtrl* GetControlCm() { return m_controlCm; }
    wxStaticText* GetTextoAlfa() { return m_textoAlfa; }
    wxTextCtrl* GetControlAlfa() { return m_controlAlfa; }
    wxStaticText* GetTextoCp() { return m_textoCp; }
    wxTextCtrl* GetControlCp() { return m_controlCp; }
    wxStaticText* GetTextoR() { return m_textoR; }
    wxTextCtrl* GetControlR() { return m_controlR; }
    wxStaticText* GetTextoPasso() { return m_textoPasso; }
    wxTextCtrl* GetControlPasso() { return m_controlPasso; }
    wxStaticText* GetTextoTempSimu() { return m_textoTempSimu; }
    wxTextCtrl* GetControlTempSimu() { return m_controlTempSimu; }
    wxStaticText* GetTextoFrequencia() { return m_textoFrequencia; }
    wxTextCtrl* GetControlFrequencia() { return m_controlFrequencia; }
    wxStaticText* GetTextoDeflexao() { return m_textoDeflexao; }
    wxTextCtrl* GetControlDeflexao() { return m_controlDeflexao; }
    wxStaticText* GetTextoF() { return m_textoF; }
    wxTextCtrl* GetControlF() { return m_controlF; }
    wxButton* GetBtnSimular() { return m_btnSimular; }
    wxButton* GetBtnLimpar() { return m_btnLimpar; }
    wxPanel* GetPanel5() { return m_panel5; }
    MainFrameBase(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = wxT("PiezoSimulator"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(600,600), long style = wxDEFAULT_FRAME_STYLE|wxBORDER_STATIC);
    virtual ~MainFrameBase();
};

#endif
